# Generated by Django 5.2.6 on 2025-09-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('kills', models.PositiveIntegerField()),
                ('accuracy', models.FloatField(help_text='Hit percentage as 0-100 value')),
                ('avg_ttk', models.FloatField(help_text='Average time to kill in milliseconds')),
                ('max_combo', models.PositiveIntegerField()),
                ('misses', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], max_length=12)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
    ]
